apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  labels:
    app: paymentservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: paymentservice
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
        - name: server
          image: ashuvduddits/paymentservice:v0.0.10