apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: frontend
  name: frontend
spec:
  containers:
    - image: ashuvduddits/frontend2
      name: frontend
      env:
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "PRODUCT_CATALOG_SERVICE_ADDR:1212"
        - name: CURRENCY_SERVICE_ADDR
          value: "CURRENCY-SERVICE-ADDR:1212"
        - name: CART_SERVICE_ADDR
          value: "CART-SERVICE-ADDR:1212"
        - name: RECOMMENDATION_SERVICE_ADDR
          value: "RECOMMENDATION-SERVICE-ADDR:1212"
        - name: CHECKOUT_SERVICE_ADDR
          value: "CHECKOUT-SERVICE-ADDR:1212"
        - name: SHIPPING_SERVICE_ADDR
          value: "SHIPPING-SERVICE-ADDR:1212"
        - name: AD_SERVICE_ADDR
          value: "AD-SERVICE-ADDR:1212"
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}